In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#数据导入
data = pd.read_csv(r'E:\kaggle_games\Iris.csv')

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


In [6]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
data.corr()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.716676     -0.397729       0.882747   
SepalLengthCm  0.716676       1.000000     -0.109369       0.871754   
SepalWidthCm  -0.397729      -0.109369      1.000000      -0.420516   
PetalLengthCm  0.882747       0.871754     -0.420516       1.000000   
PetalWidthCm   0.899759       0.817954     -0.356544       0.962757   

               PetalWidthCm  
Id                 0.899759  
SepalLengthCm      0.817954  
SepalWidthCm      -0.356544  
PetalLengthCm      0.962757  
PetalWidthCm       1.000000

In [12]:
X = data.drop('Species',axis=1)
y = data['Species']

In [16]:
#数据预处理（标签编码，数据集划分，归一化）
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
y = enc.fit_transform(y)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [22]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
scale_x_train = scale.fit_transform(X_train)
scale_x_test = scale.fit_transform(X_test)

In [23]:
y_train

array([1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1,
       2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0,
       2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1,
       1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0], dtype=int64)

In [24]:
len(y_train)

105

In [25]:
len(y_test)

45

In [40]:
#建模
#1、逻辑回归模型
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1.0, penalty='l2', tol=0.01)
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.01,
          verbose=0, warm_start=False)

In [41]:
y_predict = clf.predict(X_test)

In [42]:
y_predict

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0,
       0], dtype=int64)

In [43]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [44]:
print(confusion_matrix(y_test, y_predict))

[[16  0  0]
 [ 0 13  5]
 [ 0  0 11]]


In [45]:
print(accuracy_score(y_test, y_predict))

0.8888888888888888


In [46]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.72      0.84        18
          2       0.69      1.00      0.81        11

avg / total       0.92      0.89      0.89        45



In [47]:
#2、支持向量机模型
from sklearn.svm import SVC
clf1 = SVC(kernel='linear')
clf1.fit(X_train, y_train)

y_predict = clf1.predict(X_test)

In [48]:
print(confusion_matrix(y_test, y_predict))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [49]:
print(accuracy_score(y_test, y_predict))

1.0


In [50]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45



In [60]:
# 3、朴素贝叶斯模型
from sklearn.naive_bayes import GaussianNB
clf2 = GaussianNB()
clf2.fit(X_train, y_train)

y_predict2 = clf2.predict(X_test)

In [61]:
print(confusion_matrix(y_test, y_predict))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [62]:
print(accuracy_score(y_test, y_predict))

1.0


In [63]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45



In [90]:
# 4、k近邻模型
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier(n_neighbors=5)
clf3.fit(X_train, y_train)

y_predict = clf3.predict(X_test)

In [91]:
print(confusion_matrix(y_test, y_predict))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [92]:
print(accuracy_score(y_test, y_predict))

1.0


In [93]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45



In [94]:
#5、决策树模型
from sklearn.tree import DecisionTreeClassifier
clf4 = DecisionTreeClassifier(max_depth=4)
clf4.fit(X_train, y_train)

y_predict = clf.predict(X_test)

In [95]:
print(confusion_matrix(y_test, y_predict))

[[16  0  0]
 [ 0 13  5]
 [ 0  0 11]]


In [96]:
print(accuracy_score(y_test, y_predict))

0.8888888888888888


In [97]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.72      0.84        18
          2       0.69      1.00      0.81        11

avg / total       0.92      0.89      0.89        45

